### GENERAL SETTINGS ###

# Site settings
title: CENTEXGIS
description: "A GEOGRAPHIC INFORMATION SYSTEMS USER GROUP SERVING CENTRAL TEXAS"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "centexgis.org"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

# colors:  #in hex code if not noted else
#   primary: "#65B8F5" #"#F70031" 
primary_rgb: "13, 73, 118" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
#   secondary: "#05375C" #"#33004D"
#   link: "#1369A9"
#   link_hover: "#65B8F5"
#   footer_heading: "#ffffff"
#   footer_content: "#ffffff"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  # - title: dribbble
  #   url:
  # - title: facebook
  #   url:
  # - title: twitter
  #   url: 
  # - title: instagram
  #   url: 
  - title: linkedin
    url: https://www.linkedin.com/grp/home?gid=1786489
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - We are based in Austin, Texas
    - Questions about membership, sponsorship or just want to get in touch. Send us an email.
email: host@centexgis.org
# tel: +34 8493-4893


## GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Chris Robertson
    position: Chair
    social:
      - title: envelope #use for email address
        url: mailto:crobertson@stegerbizzell.com
  - name: Sara Smith GISP
    position: Vice-Chair
    social:
      - title: envelope #use for email address
        url: mailto:sara.smith@austintexas.gov
  - name: Jacquelyn Bilbro GISP
    position: Secretary
    social:
      - title: envelope #use for email address
        url: mailto:jacqcmb@gmail.com
  - name: Deven Rohrer GISP
    position: Vice Chair
    social:
      - title: envelope #use for email address
        url: Deven.Rohrer@atkinsglobal.com
committees:
- name: Ajay Jadhav
- name: Sumant Mallavaram
- name: Megan Yancy
- name: Sara Safavi
- name: Annie Van Zant 
- name: Dolph Scott
- name: Greg Goldman 
- name: Jennifer Moczygemba
- name: John Schulz
- name: Octavio Ulloa
- name: Ross Clark

# # Clients information. Shown on Home and About pages.
# clients:
#   - name: dribbble
#     img: client01.png
#   - name: Code is Poetry
#     img: client02.png
#   - name: Vimeo
#     img: client03.png
#   - name: VimeoPro
#     img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "CenTexGIS strives to provide the Central Texas GIS community with a forum for networking and growth. Our goal is to strengthen community bonds by bringing together public and private sector GIS professionals for knowledge sharing and support."
# Testimonial content. Shown on Home and About page. 
# testimonial:
#     message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
#     author: Marcel Newman
#     position: WEB DESIGNER - BLACKTIE.CO